name: covidvaccineapp
description: Covid vaccine distribution app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator:
  http:
  firebase_core:
  firebase_auth:
  font_awesome_flutter:
  google_fonts:
  expandable:
  cloud_firestore:
  flutter_form_builder: ^3.14.0-alpha.1
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.11.1
  modal_progress_hud:
  liquid_swipe:
  wave:
  intl: ^0.16.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Assets/