name: covidvaccineapp
description: Covid vaccine distribution app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Do not try to upgrade versions. May cause build fails due to issues in any package
dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.7+4
  http: ^0.12.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  expandable: ^4.1.4
  cloud_firestore: ^0.14.1+3
  # Hotfixed version from github as current stable and beta branches do not work with the latest version of package
  # https://github.com/danvick/flutter_form_builder/issues/382
  flutter_form_builder: ^3.14.0-alpha.1
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.11.1
  modal_progress_hud: ^0.1.3
  liquid_swipe: ^1.5.0
  wave: ^0.1.0
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Assets/
